name: Docker Image CI

on:
  push:
    branches:
    - master
    paths:
    - Dockerfile
    - .github/workflows/docker-image.yml
  pull_request:
    branches:
    - master
    paths:
    - Dockerfile
    - .github/workflows/docker-image.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: "registry.cn-qingdao.aliyuncs.com"
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: registry.cn-qingdao.aliyuncs.com/tydiczj/docker-novnc:latest
          platforms: linux/amd64,linux/arm64
